
server:
  port: 8081

spring:
  application:
    name: microservice-contabilidad
  datasource:
    url: jdbc:mysql://metro.proxy.rlwy.net:14242/railway
    username: root
    password: urGfGzSNwqtBiUurfuhtPNDlEvCgeMUS
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/