server:
  port: 9090

spring:
  application:
    name: microservice-productos
  datasource:
    url: jdbc:mysql://yamanote.proxy.rlwy.net:54713/railway
    #url: jdbc:mysql://localhost:3306/productosDb
    username: root
    password: gUtOXApWhyDWiuuqZPLEHeEVMLRqetIY
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/